n1 = int(input("Digite o primeiro número: ")) 
n2 = int(input("Digite o segundo número: ")) 
n3 = int(input("Digite o terceiro número: "))
n4 = int(input("Digite o quarto número: "))
print(n1 > n3)
print(n2 < n4)